### ISSUE TITLE
Написать бэкенд для задачи по маршрутам

### ISSUE THREAD

**Issue by Cinnamy** [Cinnamy/Urban-Topology-Analysis-Service#7]
Продумать и реализовать теорию из [документа](https://docs.google.com/document/d/1HSCBiQT7xjXZTGo4UxxBNcAv-7u3hcXNmn9Fp6gCO7g/edit), написанного аналитиком.

Для базы данных требуется:
1) Создать базу данных по описанию в [документе](https://docs.google.com/document/d/1Tjato8Mk-Es8S31wjltCpZzrxeRwo2VVtn10GhyUrEs/edit).
2) Создать парсер osm, который заполнял бы эту БД нужными данными.

**Comment by CbI3PAHb** [comment]
залито на github:

Расширена исходная БД (файл database.py) (тк создать БД, предложенную в документе [документе](https://docs.google.com/document/d/1Tjato8Mk-Es8S31wjltCpZzrxeRwo2VVtn10GhyUrEs/edit) невозможно, БД имеет такую [архитектуру](https://docs.google.com/document/d/1BufLQPNvHUi6LDD983VhN69alydKCtbqStdrH3TuSl4/edit) )

Написаны обработчики для osm.pbf файлов (файл osm_handler.py), на их основе написан парсер, который достаёт необходимую информацию из этих файлов, и заполняет БД (файл services.py).

В main.py добавлены обработчики, позволяющие получить информацию об остановках (по заданному полигону, либо по заданному списку регионов)

В services.py также написана логика, которая осуществляет запросы в БД на основе переданной информации: (мультиполигон или список регионов), а затем преобразует данные для дальнейшего использования

немного недоработано/проблемы:

Аналогичная логика для построения графов маршрутов готова только для города целиком (нет возможности получить информацию о маршрутах в пределах заданного мультиполигона)

**Comment by Cinnamy** [comment]
@eiririna исправила ошибки в [коммите](https://github.com/Cinnamy/Urban-Topology-Analysis-Service/commit/c4ca248a20e5d287ab24afb2c24cc24e946226ff) и соседних.
